Repository GEOS-ESM/swell, pull requests merged in 2024-08, with the labels that each got.

#398 Update CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement

#397 Add task to calculate ensemble mean and variance from background state
  .gitignore
  src/swell/configuration/jedi/interfaces/geos_atmosphere/geos_atmosphere.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_block.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_cube_mean_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_cube_variance_output.yaml
  src/swell/configuration/jedi/oops/ensmeanvariance.yaml
  src/swell/suites/localensembleda/flow.cylc
  src/swell/tasks/run_jedi_ensemble_mean_variance.py
  src/swell/tasks/run_jedi_hofx_executable.py
  src/swell/tasks/run_jedi_local_ensemble_da_executable.py
  src/swell/tasks/task_questions.yaml
  src/swell/test/suite_tests/localensembleda-tier1.yaml
  src/swell/utilities/render_jedi_interface_files.py
  src/swell/utilities/slurm.py
Labels: enhancement, ready for merge

#402 Add to docs a procedure note on code_tests
  docs/_sidebar.md
  docs/code_tests/code_tests.md
Labels: ready for merge
