Repository GEOS-ESM/swell, pull requests merged in 2025-05, with the labels that each got.

#552 Point directly to cylc installation on Discover
  src/swell/cylc_swell.py
Labels: bug

#559 Update mksi to latest 5.42
  src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
Labels: enhancement

#566 Remove redundancy in data/time that swell cannot handle
  src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
Labels: bug

#556 Update to work with fv3-jedi pr1335
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/analysis.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/background.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/background_ensemble.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_block.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_cube_mean_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_cube_variance_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_mean_increment_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_mean_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_members_increment_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/ensemble_members_output.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/geometry_inner.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/pseudo-model.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/stage.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/stage_cycle.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/model/varincrement1.yaml
  src/swell/configuration/jedi/interfaces/geos_atmosphere/task_questions.yaml
  src/swell/configuration/jedi/oops/LocalEnsembleDA.yaml
  src/swell/deployment/platforms/nccs_discover_cascade/task_questions.yaml
  src/swell/deployment/platforms/nccs_discover_sles15/task_questions.yaml
  src/swell/utilities/question_defaults.py
Labels: core development
